---
title: Supporting materials
date: '`r Sys.Date()`'
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE
)
options(crayon.enabled = TRUE)
old_hooks <- fansi::set_knit_hooks(knitr::knit_hooks,
                                   which = c("output", "message", "error")
)

library(fs)
# remotes::install_github("EdwinTH/dutchmasters")
library(dutchmasters)
library(ggplot2)
library(tibble)
library(dplyr)
library(patchwork)
```


## Color palette

Colors based on [`{dutchmasters}`](https://github.com/EdwinTh/dutchmasters), semi.joan's [instagram](https://www.instagram.com/semi.joan/), and Blackbird Fabrics collection of [linen](https://www.blackbirdfabrics.com/en-us/collections/linen).  

```{r palette-values}
dutch_white <- dutchmasters$pearl_earring["white(colar)"]

brick <- colorRampPalette(c("#A65746", dutch_white))

midnight <- colorRampPalette(c("#5A6E73", dutch_white))

clay <- colorRampPalette(c("#59302D", dutch_white))

taupe <- colorRampPalette(c("#BFB3A4", dutch_white))

acorn <- colorRampPalette(c("#BF895A", dutch_white))

seaweed <- colorRampPalette(c("#262001", dutch_white)) 

noil_black <- colorRampPalette(c("#0D0D0D", dutch_white))

white <- colorRampPalette(c(dutch_white, "#FFFFFF"))
```


```{r create_palette_ramp()}
create_palette_ramp <- function(x = 50){
  
  tibble::tibble(
    family = c(rep("brick", x),
               rep("midnight", x),
               rep("clay", x),
               rep("taupe", x),
               rep("acorn", x),
               rep("noil_black", x),
               rep("white", x),
               rep("seaweed", x)),
    level = c(rep(1:x, 8)),
    code = c(brick(x),
             midnight(x),
             clay(x),
             taupe(x),
             acorn(x),
             noil_black(x),
             white(x),
             seaweed(x))
  ) %>% 
    dplyr::arrange(-level)
}

palette_ramp50 <- create_palette_ramp()

saveRDS(palette_ramp50, "data/palette.RDS")
```

```{r palette-display, dpi=300}
ggplot(palette_ramp50,
       aes(x = level,
           y = family,
           color = code)) +
  geom_point(size = 18.4,
             shape = 15) +
  scale_color_identity() +
  scale_y_discrete(limits = rev) +
  labs(title = "Color palette") +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        panel.grid = element_blank(),
        axis.text.y = element_text(hjust = 0))
```

## Intro slide 

Some generative aRt ideas?  

### Gradients with dots

```{r single-gradients, dpi=300}
set.seed(24601)

split_palette <- create_palette_ramp(200) %>% 
  filter(family != "white") %>%
  arrange(family, -level) %>% 
  group_by(family) %>% 
  group_split()


purrr::map(split_palette,function(x){
  p <- ggplot(x,
              aes(x = family,
                  y = level,
                  color = code)) +
    geom_jitter(
      size = 38,
      width = .55,
      height = 0,
      alpha = 0.90) +
    scale_color_identity() +
    # scale_y_discrete(limits = rev) +
    coord_cartesian(clip = "off") +
    theme_minimal() +
    theme(axis.title = element_blank(),
          axis.text.x = element_blank(),
          panel.grid = element_blank(),
          axis.text.y = element_blank(),
          plot.background = element_rect(fill = dutch_white,
                                         colour = NA))
})

```

```{r bubble-bar-gradients, dpi=300}
set.seed(24602)

split_palette_bubble <- create_palette_ramp(200) %>% 
  filter(family != "white") %>%
  arrange(family, -level) %>% 
  group_by(family) %>% 
  group_split()


purrr::map(split_palette_bubble, function(x){
  max_level = max(x$level)
  ggplot(x,
         aes(x = family,
             y = level,
             color = code)) +
    geom_jitter(
      size = 20,
      width = 0.5,
      height = 0.2,
      alpha = 0.5) +
    scale_color_identity() +
    # scale_y_discrete(limits = rev) +
    coord_cartesian(clip = "off") +
    geom_hline(yintercept = max_level * 0.55,
               color = x$code[max_level * 0.45],
               size = 8) +
    geom_hline(yintercept = max_level * 0.5,
               color = x$code[max_level * 0.5],
               size = 10) +
    
    geom_hline(yintercept = max_level * 0.45,
               color = x$code[max_level * 0.55],
               size = 8) +
    
    theme_minimal() +
    theme(axis.title = element_blank(),
          axis.text.x = element_blank(),
          panel.grid = element_blank(),
          axis.text.y = element_blank(),
          plot.background = element_rect(fill = x$code[max_level * 0.5],
                                         colour = NA))
})

```


```{r combined-gradient, dpi=300}
set.seed(24601)

select_pal <- create_palette_ramp(400) %>% 
  filter(family %in% c("brick",
                       "clay",
                       "acorn"
                       # "taupe"
  )) %>% 
  arrange(family, level)

p <- ggplot(select_pal,
            aes(y = family,
                x = level,
                color = code)) +
  geom_jitter(
    size = 38,
    height = .45,
    width = 0,
    alpha = 0.90) +
  scale_color_identity() +
  scale_y_discrete(limits = rev) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        plot.background = element_rect(fill = dutch_white,
                                       colour = NA))

p + (p + scale_x_reverse())
```
## Satisfying gif candidates  


<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/vc3yjx/sealing_a_gap_with_silicone/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/v4ue9y/this_transition_of_colour/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/uxtpz2/hay_this_is_pretty_satisfying/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/vctpqm/self_aligining_nails_how/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/v4mn16/log_splitting_the_water/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/uw2xah/the_making_of_pastry_art/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/u92s9k/new_warehouse_floor/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/qtqeys/cleaning_up_the_lines/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="620" width="640" scrolling="no"></iframe>

<iframe id="reddit-embed" src="https://www.redditmedia.com/r/oddlysatisfying/comments/taxpo9/i_work_in_a_steel_mill_and_we_were_rolling_one_of/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" height="446" width="640" scrolling="no"></iframe>

<div style='position:relative; padding-bottom:calc(177.78% + 44px)'><iframe src='https://gfycat.com/ifr/FlawlessNiftyCatbird' frameborder='0' scrolling='no' width='100%' height='100%' style='position:absolute;top:0;left:0;' allowfullscreen></iframe></div>



<div style='position:relative; padding-bottom:calc(125.00% + 44px)'><iframe src='https://gfycat.com/ifr/NeedyGivingBufeo' frameborder='0' scrolling='no' width='100%' height='100%' style='position:absolute;top:0;left:0;' allowfullscreen></iframe></div>